sudo: required
dist: trusty
language: node_js

node_js:
- '6.9.1'
- 'stable'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - google-chrome-stable
    - g++-4.8

cache:
  directories:
  - node_modules

env:
  matrix:
  - EMBER_TRY_SCENARIO=ember-lts-2.4
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-default
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  global:
    - CXX=g++-4.8
    - secure: FrdBXx8NhDGpucvjTVLVPEgd2M3zlPMixzMePwturWuKqY/UdjRRlrSV5niGEwd/wuJMua6/qPCy7Q2wC1mck4l1SAm65mUdf5AB6uod1znf/Z/fub1bj2O2EU1Ma1xOzaQLFkkpYFzz8pQPVvqdJoJuKmDqd1uF/q4V6RgREoY5J0N1cLD/k7HMaDJCJE2L+aidjqWh83p2n8XYS7GxhKXDJQphTQBGb8phM+fANzrC4vpKVccM3DSG9PINbxlvU5EViMD2nYj5xKebCyt7gPfFiooSJLzN7lVOqAiVTolOGXEudweeUWt5Bb/gYZmraYLjOf+OlaA8CdaeWGYw7nTzfAENrL9V/SD00dHL/GDT0sBbZGn7r59QJWFUlfgwGvrymPqszJj0ibhl2pLDdNmG3JJZqZ1T4kw/sVUEOZ8cK2Y7jb0lvUJSZqNztbDP66JzO0WVfKTpE1WyACrc7s1CjOWHvVGODu567JlLPcYnzfR0a3f72XRE9LQ3C3rPxulcSF9TgikclZVbVhVU+eqI5JY+WHmDt9/WYNbF8VRGFoaBnhTtX9XAiIhTeTCfsHjwOiNtmOlS1kD/SbcWgoYYL+grqSkaoMmP0r2XBzi9NL2ae8w3d+Vp2KdS40Dp+oM8urICFOQaZ+kkyGBP5sMQ52i1dIqqUxE2gP0rrSM=

matrix:
  fast_finish: true
  allow_failures:
  - env: EMBER_TRY_SCENARIO=ember-release
  - env: EMBER_TRY_SCENARIO=ember-beta
  - env: EMBER_TRY_SCENARIO=ember-canary
  - node_js: 'stable'

before_install:
- npm config set spin false
- npm install -g coveralls pr-bumper@^1.0.0
- $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

install:
- $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3 # give xvfb some time to start

script:
- $(npm root -g)/pr-bumper/.travis/maybe-test.sh
- .travis/maybe-bump-version.sh

after_success:
- .travis/maybe-publish-coverage.sh
- .travis/maybe-publish-gh-pages.sh

deploy:
  provider: npm
  email: npm.ciena@gmail.com
  skip_cleanup: true
  api_key:
    secure: ZSBRYvPUWjHTNSlASf6inTFoxs+FVnZeWQEyv0985/lG/Fr+4h+sPu5airMU/gO8JLycmFkpxP6rSsUNDMBBJPhHVapPlBk2S0qgqeJWX3eo2FKIOU3JKmGy7+MOtrVSm9Ul+DhZsYCR+lbw84tWMXkqSbhIBYnOPqpjJqJZZHqgPyPHBoKE2u3QecdOBpy971GL+Yf7GWS1uFD3qbi1rNnOdoLg0+7eOVN2Ccoiyo3ToEsIKUBUeIB4cBTgjsLPD6Yq/vO5gf/OmrGjU8odVUKc2sV4ZHA5J6yIM+xxjQM6Y54q+z39mFnvQjXG+kNGn523uWJFVNCEW2WbVRqk2w6FUxYYuxqqRy7vdsWsU+d9Pp0nhK4psWmnU3CuUYsiwPx1/rgfKdZZo8EU2hSDUivOUzlZgMg1a0wBceP+TW9ZSe/XtXQdoiOyc3CmhVNljCcktwJyFIN64FJfyos60gdGmy9Jr5qkM1JcvUfa7BvsRnzt26AouI/EXkJ2bU24cKCgITkGh9NOJLn3AVxRg2tmlt/76irT1iaDCVekjDeUSX/arULvSPZRWidjbnDyNbyVFW5yxFTnr3ykDjWBg39tSj+1iOqWqqCyssqH1lP7eE5j5hdHvKIwpGyVm/ZgSQ/5pOduSW+0Z75J+guHLpGhlJ6bzD8pGwdaLBPDjB0=
  on:
    all_branches: true
    condition: "$EMBER_TRY_SCENARIO = 'ember-default'"
    node: '6.9.1'
    tags: true

notifications:
  slack:
    secure: anXx8jkhC/gQg1VpTNtkf4zEvbkdslvleoBrdR0f943fye3Ue/Iw04pk7iaQJTA6O6/n6zdo7A5GeCch7XURAW0fSPprkz6HITHG01DioxEVslCS7zwjZ1GT80WWv7BWZIAEEKliAwiR0iFqG+0NgtwArQGCZE7X60GuPyq7cOuAQY/HzJl3jyB6whd4JRleaiIDHi8pCiqUPcsJ2eLdiWKXy0UPdNncZ45H5dWqU6fjJQ+CLMWeBrmtu4TVbpRIFrFVVigWuXYBPIoYHEmsqwsU074RIvzQWeJFyN7swumrWszlz/9GkAYZNdnTF9yhmCvJt/DMDWQ3qAHVyspgUNQd2J4LFvP1C4i9qt3xuAJKJoCHoNU0oltESWtGFE1f17zbh0klvl671OLGXsyMe+Y87tDQ1mraLRGKp/7xzoLEQyvaClioS7GgV/HbwanW/0wgianTXTlatoBUnqsANyFjds+7b8nM7gsZ7sCgm9ZHpMgOGtmrm1EP26aJbRi4Te7G0n//Yq+BY7E4H8MmteMv6H6S+xVZcZSlp8yenv6q3XVqsEumZBrH93qnx6lUw2RjTG3G02jMiW8X8LdHG3iL2aUW/Gte2/3h+PtlpiSx9uyT2BH6R+DWvMZhPxV54U2QlmNdt8d5J59vZ3s6QWVhoAN7zevZNuOYB2Ru+ro=
